In [1]:
import pandas as pd

In [9]:
def combine_season_games(season1, season2):
    stats_folder = ''
    file_name = 'season_games'
    file_type = '.xlsx'
    df1 = pd.read_excel("{}{}_{}{}".format(stats_folder, season1, file_name, file_type))
    df1 = df1[df1['schedule.playedStatus'] == 'COMPLETED']
    df2 = pd.read_excel("{}{}_{}{}".format(stats_folder, season2, file_name, file_type))
    # df2 = df2[df2['schedule.playedStatus'] == 'COMPLETED']
    df = df1.append(df2, ignore_index=True)
    dropped = ['schedule.attendance', 'schedule.broadcasters', 'schedule.delayedOrPostponedReason', 'schedule.endedTime', 'schedule.officials', 'schedule.originalStartTime', 'schedule.weather', 'score.currentIntermission', 'score.currentQuarter', 'score.currentQuarterSecondsRemaining', 'score.quarters']
    df = df[df.columns.drop(dropped)]
    output_folder = ''
    output_format = 'csv'
    # save the df
    df.to_csv("{}{}_{}.{}".format(output_folder, 'combined', file_name, output_format), encoding='utf-8', index=False)
    # return the df for debugging
    # return df

In [10]:
# 17-18 season 1229 games
# 18-19 season 378 games already finished
df = combine_season_games('1718', '1819')
# 2018-11-16T01:00:00.000Z
# 2018-12-01T00:00:00.000Z
# df[(df['schedule.startTime'] >= '2018-11-16T01:00:00.000Z') & (df['schedule.startTime'] < '2018-12-01T00:00:00.000Z')]
# df[df['schedule.startTime'] > df.loc[1600]['schedule.startTime']]

In [4]:
stats_folder = 'team_game_logs_'
file_name = 'team_game_log'
season1 = '1718'
season2 = '1819'
team_name = 'ATL'
file_type = '.xlsx'
df1 = pd.read_excel("{}{}/{}_{}{}".format(stats_folder, season1, file_name, team_name, file_type))
df2 = pd.read_excel("{}{}/{}_{}{}".format(stats_folder, season2, file_name, team_name, file_type))

In [16]:
df_ATL = df1.append(df2, ignore_index=True)
df_ATL[(df_ATL['game.awayTeamAbbreviation'] == 'ATL') & (df_ATL['game.id'] == 47783)]
# df_ATL[df_ATL['game.startTime'] < '2018-11-16T02:00:00.000Z'].tail(5)
# df_ATL[df_ATL['game.startTime'] < df.loc[1443]['schedule.startTime']].tail(5).mean()
df_tmp = df_ATL[df_ATL['game.startTime'] < df.loc[30]['schedule.startTime']].sort_values(by='game.startTime', ascending=False)[:5]
print(df_tmp.shape)
print('size: ', df_tmp.shape[0])
for i in range(5):
    if df_tmp.shape[0] < i:
        continue
    print(df_tmp.shape[0], i)

(2, 73)
size:  2
2 0
2 1
2 2

In [77]:
df = df1.append(df2, ignore_index=True)

In [78]:
df[df['game.startTime'] < df.loc[5]['game.startTime']]

,game.awayTeamAbbreviation,game.homeTeamAbbreviation,game.id,game.startTime,stats.defense.blk,stats.defense.blkAgainst,stats.defense.blkAgainstPerGame,stats.defense.blkPerGame,stats.defense.ptsAgainst,stats.defense.ptsAgainstPerGame,...,stats.rebounds.offReb,stats.rebounds.offRebPerGame,stats.rebounds.reb,stats.rebounds.rebPerGame,stats.standings.gamesBack,stats.standings.losses,stats.standings.winPct,stats.standings.wins,team.abbreviation,team.id
0,ATL,DAL,42078,2017-10-19T00:30:00.000Z,6,4,4,6,111,111,...,14,14,54,54,0,0,1,1,ATL,91
1,ATL,CHA,42089,2017-10-20T23:00:00.000Z,4,4,4,4,109,109,...,15,15,49,49,0,1,0,0,ATL,91
2,ATL,BRO,42107,2017-10-22T19:30:00.000Z,2,8,8,2,116,116,...,23,23,58,58,0,1,0,0,ATL,91
3,ATL,MIA,42111,2017-10-23T23:30:00.000Z,1,6,6,1,104,104,...,11,11,47,47,0,1,0,0,ATL,91
4,ATL,CHI,42134,2017-10-27T00:00:00.000Z,5,4,4,5,91,91,...,7,7,44,44,0,1,0,0,ATL,91

In [24]:
l1 = df.columns.values.tolist()
print(len(df.columns.values.tolist()))
for i in df.columns.values.tolist():
    print(i)

73
game.awayTeamAbbreviation
game.homeTeamAbbreviation
game.id
game.startTime
stats.defense.blk
stats.defense.blkAgainst
stats.defense.blkAgainstPerGame
stats.defense.blkPerGame
stats.defense.ptsAgainst
stats.defense.ptsAgainstPerGame
stats.defense.stl
stats.defense.stlPerGame
stats.defense.tov
stats.defense.tovPerGame
stats.fieldGoals.fg2PtAtt
stats.fieldGoals.fg2PtAttPerGame
stats.fieldGoals.fg2PtMade
stats.fieldGoals.fg2PtMadePerGame
stats.fieldGoals.fg2PtPct
stats.fieldGoals.fg3PtAtt
stats.fieldGoals.fg3PtAttPerGame
stats.fieldGoals.fg3PtMade
stats.fieldGoals.fg3PtMadePerGame
stats.fieldGoals.fg3PtPct
stats.fieldGoals.fgAtt
stats.fieldGoals.fgAttPerGame
stats.fieldGoals.fgMade
stats.fieldGoals.fgMadePerGame
stats.fieldGoals.fgPct
stats.freeThrows.ftAtt
stats.freeThrows.ftAttPerGame
stats.freeThrows.ftMade
stats.freeThrows.ftMadePerGame
stats.freeThrows.ftPct
stats.miscellaneous.ejections
stats.miscellaneous.foulFlag1
stats.miscellaneous.foulFlag1Drawn
stats.miscellaneous.foulFlag1DrawnPerGame
stats.miscellaneous.foulFlag1PerGame
stats.miscellaneous.foulFlag2
stats.miscellaneous.foulFlag2Drawn
stats.miscellaneous.foulFlag2DrawnPerGame
stats.miscellaneous.foulFlag2PerGame
stats.miscellaneous.foulPers
stats.miscellaneous.foulPersDrawn
stats.miscellaneous.foulPersDrawnPerGame
stats.miscellaneous.foulPersPerGame
stats.miscellaneous.foulTech
stats.miscellaneous.foulTechDrawn
stats.miscellaneous.foulTechDrawnPerGame
stats.miscellaneous.foulTechPerGame
stats.miscellaneous.fouls
stats.miscellaneous.foulsDrawn
stats.miscellaneous.foulsDrawnPerGame
stats.miscellaneous.foulsPerGame
stats.miscellaneous.plusMinus
stats.miscellaneous.plusMinusPerGame
stats.offense.ast
stats.offense.astPerGame
stats.offense.pts
stats.offense.ptsPerGame
stats.rebounds.defReb
stats.rebounds.defRebPerGame
stats.rebounds.offReb
stats.rebounds.offRebPerGame
stats.rebounds.reb
stats.rebounds.rebPerGame
stats.standings.gamesBack
stats.standings.losses
stats.standings.winPct
stats.standings.wins
team.abbreviation
team.id

In [25]:
df = df[df.columns.drop(list(df.filter(regex='PerGame')))]

In [26]:
l2 = df.columns.values.tolist()
print(len(df.columns.values.tolist()))
for i in df.columns.values.tolist():
    print(i)

44
game.awayTeamAbbreviation
game.homeTeamAbbreviation
game.id
game.startTime
stats.defense.blk
stats.defense.blkAgainst
stats.defense.ptsAgainst
stats.defense.stl
stats.defense.tov
stats.fieldGoals.fg2PtAtt
stats.fieldGoals.fg2PtMade
stats.fieldGoals.fg2PtPct
stats.fieldGoals.fg3PtAtt
stats.fieldGoals.fg3PtMade
stats.fieldGoals.fg3PtPct
stats.fieldGoals.fgAtt
stats.fieldGoals.fgMade
stats.fieldGoals.fgPct
stats.freeThrows.ftAtt
stats.freeThrows.ftMade
stats.freeThrows.ftPct
stats.miscellaneous.ejections
stats.miscellaneous.foulFlag1
stats.miscellaneous.foulFlag1Drawn
stats.miscellaneous.foulFlag2
stats.miscellaneous.foulFlag2Drawn
stats.miscellaneous.foulPers
stats.miscellaneous.foulPersDrawn
stats.miscellaneous.foulTech
stats.miscellaneous.foulTechDrawn
stats.miscellaneous.fouls
stats.miscellaneous.foulsDrawn
stats.miscellaneous.plusMinus
stats.offense.ast
stats.offense.pts
stats.rebounds.defReb
stats.rebounds.offReb
stats.rebounds.reb
stats.standings.gamesBack
stats.standings.losses
stats.standings.winPct
stats.standings.wins
team.abbreviation
team.id

In [29]:
l_diff = [i for i in l1 if i not in l2]
print(len(l_diff))
for i in l_diff:
    print(i)

29
stats.defense.blkAgainstPerGame
stats.defense.blkPerGame
stats.defense.ptsAgainstPerGame
stats.defense.stlPerGame
stats.defense.tovPerGame
stats.fieldGoals.fg2PtAttPerGame
stats.fieldGoals.fg2PtMadePerGame
stats.fieldGoals.fg3PtAttPerGame
stats.fieldGoals.fg3PtMadePerGame
stats.fieldGoals.fgAttPerGame
stats.fieldGoals.fgMadePerGame
stats.freeThrows.ftAttPerGame
stats.freeThrows.ftMadePerGame
stats.miscellaneous.foulFlag1DrawnPerGame
stats.miscellaneous.foulFlag1PerGame
stats.miscellaneous.foulFlag2DrawnPerGame
stats.miscellaneous.foulFlag2PerGame
stats.miscellaneous.foulPersDrawnPerGame
stats.miscellaneous.foulPersPerGame
stats.miscellaneous.foulTechDrawnPerGame
stats.miscellaneous.foulTechPerGame
stats.miscellaneous.foulsDrawnPerGame
stats.miscellaneous.foulsPerGame
stats.miscellaneous.plusMinusPerGame
stats.offense.astPerGame
stats.offense.ptsPerGame
stats.rebounds.defRebPerGame
stats.rebounds.offRebPerGame
stats.rebounds.rebPerGame

In [32]:
l3 = []
for i in l_diff:
    l3.append(i.split('Pergame')[0])
print(len(l3))

29

In [36]:
l4 = [i for i in l3 if i in l1]
print(len(l4))

29

In [3]:
def combine_stats(team_name):
    stats_folder = 'team_game_logs_'
    file_name = 'team_game_log'
    season1 = '1718'
    season2 = '1819'
    file_type = '.xlsx'
    df1 = pd.read_excel("{}{}/{}_{}{}".format(stats_folder, season1, file_name, team_name, file_type))
    df2 = pd.read_excel("{}{}/{}_{}{}".format(stats_folder, season2, file_name, team_name, file_type))
    df = df1.append(df2, ignore_index=True)
    df = df[df.columns.drop(list(df.filter(regex='PerGame')))]
    output_folder = 'team_game_logs_combined'
    output_format = 'csv'
    l_id = df['team.id'].tolist()
    print(team_name, set(l_id))
    df.to_csv("{}/{}_{}.{}".format(output_folder, file_name, team_name, output_format), encoding='utf-8', index=False)
    # return df

In [64]:
df = combine_stats('ATL')

In [65]:
df.sort_values(by='game.startTime', ascending=False)[:5]

,game.awayTeamAbbreviation,game.homeTeamAbbreviation,game.id,game.startTime,stats.defense.blk,stats.defense.blkAgainst,stats.defense.ptsAgainst,stats.defense.stl,stats.defense.tov,stats.fieldGoals.fg2PtAtt,...,stats.offense.pts,stats.rebounds.defReb,stats.rebounds.offReb,stats.rebounds.reb,stats.standings.gamesBack,stats.standings.losses,stats.standings.winPct,stats.standings.wins,team.abbreviation,team.id
106,WAS,ATL,47926,2018-12-06T00:30:00.000Z,4,4,131,13,17,54,...,117,35,8,43,0,1,0,0,ATL,91
105,GSW,ATL,47913,2018-12-04T00:30:00.000Z,4,8,128,10,18,64,...,111,26,9,35,0,1,0,0,ATL,91
104,ATL,OKL,47894,2018-12-01T01:00:00.000Z,3,7,124,10,15,47,...,80,24,9,33,0,1,0,0,ATL,91
103,ATL,CHA,47875,2018-11-29T00:00:00.000Z,8,5,108,11,19,49,...,94,38,16,54,0,1,0,0,ATL,91
102,ATL,MIA,47871,2018-11-28T00:30:00.000Z,7,3,113,13,24,49,...,115,36,10,46,0,0,1,1,ATL,91

In [67]:
print(df.loc[0])
df[(df['game.id'] == df.loc[0]['game.id'])]

game.awayTeamAbbreviation                                  ATL
game.homeTeamAbbreviation                                  DAL
game.id                                                  42078
game.startTime                        2017-10-19T00:30:00.000Z
stats.defense.blk                                            6
stats.defense.blkAgainst                                     4
stats.defense.ptsAgainst                                   111
stats.defense.stl                                           11
stats.defense.tov                                           13
stats.fieldGoals.fg2PtAtt                                   76
stats.fieldGoals.fg2PtMade                                  39
stats.fieldGoals.fg2PtPct                                 51.3
stats.fieldGoals.fg3PtAtt                                   18
stats.fieldGoals.fg3PtMade                                   9
stats.fieldGoals.fg3PtPct                                   50
stats.fieldGoals.fgAtt                                      94
stats.fieldGoals.fgMade                                     48
stats.fieldGoals.fgPct                                    51.1
stats.freeThrows.ftAtt                                      15
stats.freeThrows.ftMade                                     12
stats.freeThrows.ftPct                                      80
stats.miscellaneous.ejections                                0
stats.miscellaneous.foulFlag1                                0
stats.miscellaneous.foulFlag1Drawn                           0
stats.miscellaneous.foulFlag2                                0
stats.miscellaneous.foulFlag2Drawn                           0
stats.miscellaneous.foulPers                                18
stats.miscellaneous.foulPersDrawn                           19
stats.miscellaneous.foulTech                                18
stats.miscellaneous.foulTechDrawn                            0
stats.miscellaneous.fouls                                   20
stats.miscellaneous.foulsDrawn                              19
stats.miscellaneous.plusMinus                                6
stats.offense.ast                                           20
stats.offense.pts                                          117
stats.rebounds.defReb                                       39
stats.rebounds.offReb                                       14
stats.rebounds.reb                                          54
stats.standings.gamesBack                                    0
stats.standings.losses                                       0
stats.standings.winPct                                       1
stats.standings.wins                                         1
team.abbreviation                                          ATL
team.id                                                     91
Name: 0, dtype: object

,game.awayTeamAbbreviation,game.homeTeamAbbreviation,game.id,game.startTime,stats.defense.blk,stats.defense.blkAgainst,stats.defense.ptsAgainst,stats.defense.stl,stats.defense.tov,stats.fieldGoals.fg2PtAtt,...,stats.offense.pts,stats.rebounds.defReb,stats.rebounds.offReb,stats.rebounds.reb,stats.standings.gamesBack,stats.standings.losses,stats.standings.winPct,stats.standings.wins,team.abbreviation,team.id
0,ATL,DAL,42078,2017-10-19T00:30:00.000Z,6,4,111,11,13,76,...,117,39,14,54,0,0,1,1,ATL,91

In [70]:
l_id = df['team.id'].tolist()
print(set(l_id))

{91}

In [4]:
teams_all = '''ATL
BOS
BRO
CHA
CHI
CLE
DAL
DEN
DET
GSW
HOU
IND
LAC
LAL
MEM
MIA
MIL
MIN
NOP
NYK
OKL
ORL
PHI
PHX
POR
SAC
SAS
TOR
UTA
WAS
'''
teams = teams_all.splitlines()
for team in teams:
    combine_stats(team)

ATL {91}
BOS {82}
BRO {84}
CHA {93}
CHI {89}
CLE {86}
DAL {108}
DEN {99}
DET {88}
GSW {101}
HOU {109}
IND {87}
LAC {102}
LAL {105}
MEM {107}
MIA {92}
MIL {90}
MIN {100}
NOP {110}
NYK {83}
OKL {96}
ORL {95}
PHI {85}
PHX {104}
POR {97}
SAC {103}
SAS {106}
TOR {81}
UTA {98}
WAS {94}